# Generated by Django 5.0.2 on 2025-04-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favoritejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='format_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_feedback',
            field=models.TextField(blank=True),
        ),
    ]
